/**
 * Catalogue contract.
 *
 * Mirrors data/catalog.json exactly — that file is generated by
 * tools/build-catalog.py and is the single source of truth shared by the
 * Next.js frontend and the WordPress plugin.
 *
 * Shapes follow the live store's WooCommerce model: variable products with a
 * price range and a pack-size ladder, belonging to one or more product
 * categories addressed as /product-category/<slug>/.
 */

import type { IconName, Tone } from './types';

export type BadgeTone = 'sale' | 'hot' | 'new' | 'save';

/** One purchasable variation of a variable product. */
export interface Pack {
  label: string;
  units: number;
  price: number;
  priceLabel: string;
  unitLabel: string;
}

export interface GuidePoint {
  title: string;
  body: string;
}

export interface CategoryGuide {
  title: string;
  intro: string;
  points: GuidePoint[];
}

export interface FaqEntry {
  question: string;
  answer: string;
}

export interface UsageBlock {
  title: string;
  body: string;
}

export interface CatalogCategory {
  slug: string;
  name: string;
  icon: IconName;
  tone: Tone;
  description: string;
  href: string;
  productCount: number;
  /** Buying guide rendered beneath the product grid. */
  guide: CategoryGuide;
  faqs: FaqEntry[];
  /** Sibling category slugs for cross-navigation. */
  related: string[];
}

export interface CatalogProduct {
  slug: string;
  name: string;
  /** Active ingredient, shown as the card subtitle. */
  subtitle: string;
  form: string;
  categories: string[];
  primaryCategory: string;
  priceMin: number;
  priceMax: number;
  /** Pre-formatted range, e.g. "$77.00 – $363.00". */
  priceLabel: string;
  packs: Pack[];
  rating: number;
  reviewCount: number;
  /** '' when the product carries no badge. */
  badge: string;
  description: string;
  specs: Record<string, string>;
  /** What the medicine is prescribed for, reused in page copy. */
  indication: string;
  faqs: FaqEntry[];
  usage: UsageBlock[];
  /** Star rating counts keyed '5'..'1'. */
  reviewBreakdown: Record<string, number>;
  /** Thumbnail gallery. */
  gallery: string[];
  href: string;
  image: { src: string; alt: string };
}

export interface Catalog {
  categories: CatalogCategory[];
  products: CatalogProduct[];
  /** Shown wherever medical guidance appears. */
  disclaimer: string;
}

/** Multi-select facets derived from the catalogue. */
export interface Facet {
  key: FacetKey;
  label: string;
  options: { value: string; count: number }[];
}

export type FacetKey = 'ingredient' | 'form' | 'manufacturer';

export type FacetState = Record<FacetKey, string[]>;

export type SortKey = 'popular' | 'rating' | 'price-asc' | 'price-desc' | 'name';
