/**
 * Catalogue contract.
 *
 * Mirrors data/catalog.json exactly — that file is generated by
 * tools/build-catalog.py and is the single source of truth shared by the
 * Next.js frontend and the WordPress plugin.
 *
 * Shapes follow the live store's WooCommerce model: variable products with a
 * price range and a pack-size ladder, belonging to one or more product
 * categories addressed as /product-category/<slug>/.
 */

import type { IconName, Tone } from './types';

export type BadgeTone = 'sale' | 'hot' | 'new' | 'save';

/** One purchasable variation of a variable product. */
export interface Pack {
  label: string;
  units: number;
  price: number;
  priceLabel: string;
  unitLabel: string;
}

export interface CatalogCategory {
  slug: string;
  name: string;
  icon: IconName;
  tone: Tone;
  description: string;
  href: string;
  productCount: number;
}

export interface CatalogProduct {
  slug: string;
  name: string;
  /** Active ingredient, shown as the card subtitle. */
  subtitle: string;
  form: string;
  categories: string[];
  primaryCategory: string;
  priceMin: number;
  priceMax: number;
  /** Pre-formatted range, e.g. "$77.00 – $363.00". */
  priceLabel: string;
  packs: Pack[];
  rating: number;
  reviewCount: number;
  /** '' when the product carries no badge. */
  badge: string;
  description: string;
  specs: Record<string, string>;
  href: string;
  image: { src: string; alt: string };
}

export interface Catalog {
  categories: CatalogCategory[];
  products: CatalogProduct[];
}

export type SortKey = 'popular' | 'rating' | 'price-asc' | 'price-desc' | 'name';
